//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class afm
    {
        public int kwd { get; set; }
        public Nullable<int> etaireia { get; set; }
        public string epixirisi { get; set; }
        public string xenodoxeio { get; set; }
        public string dieuthinsi { get; set; }
        public string tilefono { get; set; }
        public string afm1 { get; set; }
        public string doy { get; set; }
        public bool eikoniko { get; set; }
        public Nullable<int> apykwd { get; set; }
        public Nullable<int> timolkwd { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    }
}
