//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class dwmatia
    {
        public dwmatia()
        {
            this.kratiseis = new HashSet<kratiseis>();
            this.status = new HashSet<status>();
        }
    
        public string arithmos { get; set; }
        public Nullable<int> katigoria { get; set; }
        public Nullable<short> klines { get; set; }
        public Nullable<int> thea { get; set; }
        public string perigrafi { get; set; }
        public Nullable<int> afm { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
        public Nullable<int> property { get; set; }
        public Nullable<int> scheduler { get; set; }
    
        public virtual tblproperty tblproperty { get; set; }
        public virtual ICollection<kratiseis> kratiseis { get; set; }
        public virtual ICollection<status> status { get; set; }
    }
}
