//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class enilikes
    {
        public int kwd { get; set; }
        public Nullable<int> kratisi { get; set; }
        public string onomateponimo { get; set; }
        public string patronimo { get; set; }
        public Nullable<System.DateTime> genisi { get; set; }
        public Nullable<short> ethnikotita { get; set; }
        public string diabatirio { get; set; }
        public Nullable<System.DateTime> ekdosi { get; set; }
        public string toposgenisis { get; set; }
        public string dieuthinsi { get; set; }
        public string poli { get; set; }
        public Nullable<short> xora { get; set; }
        public string epaggelma { get; set; }
        public string tilefono { get; set; }
        public string prosfonisi { get; set; }
        public string simiosi { get; set; }
        public Nullable<byte> palaios { get; set; }
        public Nullable<System.DateTime> eorti { get; set; }
        public Nullable<System.DateTime> gamos { get; set; }
        public string axiologisi { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    
        public virtual kratiseis kratiseis { get; set; }
        public virtual kratiseis kratiseis1 { get; set; }
    }
}
