//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class etaireia
    {
        public int kwd { get; set; }
        public string epixirisi { get; set; }
        public string xenodoxeio { get; set; }
        public string dieuthinsi { get; set; }
        public string tilefono { get; set; }
        public string afm { get; set; }
        public string doy { get; set; }
        public Nullable<float> fpatrofis1 { get; set; }
        public Nullable<float> fpatrofis2 { get; set; }
        public Nullable<float> fpatrofis3 { get; set; }
        public Nullable<float> fpatrofis4 { get; set; }
        public Nullable<float> dimforos1 { get; set; }
        public Nullable<float> dimforos2 { get; set; }
        public Nullable<float> fparepid1 { get; set; }
        public Nullable<float> fparepid2 { get; set; }
        public Nullable<float> fpatmima1 { get; set; }
        public Nullable<float> fpatmima2 { get; set; }
        public Nullable<float> fpatmima3 { get; set; }
        public Nullable<float> fpatmima4 { get; set; }
        public Nullable<float> fpatmima5 { get; set; }
        public Nullable<short> extras { get; set; }
        public bool guaranti { get; set; }
        public Nullable<short> aakratisis { get; set; }
        public Nullable<short> mindwmatia { get; set; }
        public Nullable<short> maxdwmatia { get; set; }
        public Nullable<byte> xklino { get; set; }
        public Nullable<short> minklines { get; set; }
        public Nullable<short> maxklines { get; set; }
        public bool ktimis { get; set; }
        public Nullable<byte> biblportas { get; set; }
        public string theorisiapy { get; set; }
        public string timologia { get; set; }
        public Nullable<int> aage { get; set; }
        public Nullable<int> aaapy { get; set; }
        public bool biblportastimes { get; set; }
        public Nullable<System.DateTime> imeromergasias { get; set; }
        public Nullable<System.DateTime> kleismenidate { get; set; }
        public Nullable<byte> ektportasflag { get; set; }
        public Nullable<byte> ektportasapyflag { get; set; }
        public Nullable<short> aagramatio { get; set; }
        public Nullable<short> aabapy { get; set; }
        public string fakelosbackup { get; set; }
        public string basi { get; set; }
        public string version { get; set; }
        public string connectionstring { get; set; }
        public Nullable<int> apykwd { get; set; }
        public Nullable<int> timolkwd { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
        public Nullable<int> property { get; set; }
    
        public virtual tblproperty tblproperty { get; set; }
    }
}
