//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class forosdiamonis
    {
        public int kwd { get; set; }
        public int etaireia { get; set; }
        public int kratisi { get; set; }
        public Nullable<System.DateTime> imerominia { get; set; }
        public Nullable<short> arithmos { get; set; }
        public string onoma { get; set; }
        public string drastiriotita { get; set; }
        public string dieuthinsi { get; set; }
        public string afm { get; set; }
        public string doy { get; set; }
        public Nullable<System.DateTime> afixi { get; set; }
        public Nullable<System.DateTime> anaxwrisi { get; set; }
        public Nullable<float> days { get; set; }
        public string room { get; set; }
        public Nullable<int> timologio { get; set; }
        public string apy { get; set; }
        public string parastatiko { get; set; }
        public bool akyromeno { get; set; }
        public Nullable<float> foros { get; set; }
        public string pliromi { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    }
}
