//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class kratiseis
    {
        public kratiseis()
        {
            this.enilikes1 = new HashSet<enilikes>();
            this.enilikes2 = new HashSet<enilikes>();
            this.paidia1 = new HashSet<paidia>();
            this.timeskratisis = new HashSet<timeskratisis>();
        }
    
        public int kwd { get; set; }
        public Nullable<int> dbhotel { get; set; }
        public Nullable<System.DateTime> imeromkratisis { get; set; }
        public Nullable<short> etos { get; set; }
        public Nullable<short> arithmos { get; set; }
        public Nullable<int> simbolaio { get; set; }
        public Nullable<int> praktoreio { get; set; }
        public Nullable<int> praktimologio { get; set; }
        public bool privatimologio { get; set; }
        public string voucher { get; set; }
        public Nullable<short> enilikes { get; set; }
        public Nullable<short> paidia { get; set; }
        public Nullable<short> ethnikotites { get; set; }
        public Nullable<byte> anzethnikotites { get; set; }
        public Nullable<short> ethnikotites2 { get; set; }
        public Nullable<byte> anzethnikotites2 { get; set; }
        public string tilefonomem { get; set; }
        public Nullable<System.DateTime> epithimdate { get; set; }
        public string epithimia { get; set; }
        public Nullable<short> simetoxi { get; set; }
        public Nullable<float> prokataboli { get; set; }
        public Nullable<System.DateTime> prokatdate { get; set; }
        public Nullable<System.DateTime> afixi { get; set; }
        public Nullable<System.DateTime> wra { get; set; }
        public Nullable<System.DateTime> anaxwrisi { get; set; }
        public Nullable<int> klines { get; set; }
        public Nullable<int> tipos { get; set; }
        public bool guarantie { get; set; }
        public string dwmatio { get; set; }
        public string pliromi { get; set; }
        public bool biblioportas { get; set; }
        public Nullable<float> synolo { get; set; }
        public bool checkin { get; set; }
        public Nullable<System.DateTime> datein { get; set; }
        public bool checkout { get; set; }
        public Nullable<System.DateTime> dateout { get; set; }
        public bool allagesdwmatiwn { get; set; }
        public bool ekptosi { get; set; }
        public Nullable<float> ekptposo { get; set; }
        public Nullable<float> ekptpososto { get; set; }
        public Nullable<float> ekptimeres { get; set; }
        public Nullable<float> fee { get; set; }
        public Nullable<byte> timologio { get; set; }
        public Nullable<short> apy { get; set; }
        public Nullable<int> identifikation { get; set; }
        public Nullable<int> parastatiko { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
        public Nullable<int> property { get; set; }
        public Nullable<byte> state { get; set; }
    
        public virtual dwmatia dwmatia { get; set; }
        public virtual ICollection<enilikes> enilikes1 { get; set; }
        public virtual ICollection<enilikes> enilikes2 { get; set; }
        public virtual ethnikotites ethnikotites1 { get; set; }
        public virtual ICollection<paidia> paidia1 { get; set; }
        public virtual praktoreia praktoreia { get; set; }
        public virtual praktoreia praktoreia1 { get; set; }
        public virtual tblproperty tblproperty { get; set; }
        public virtual simbolaia simbolaia { get; set; }
        public virtual ICollection<timeskratisis> timeskratisis { get; set; }
        public virtual tipoi tipoi { get; set; }
    }
}
