//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class praktoreia
    {
        public praktoreia()
        {
            this.kratiseis = new HashSet<kratiseis>();
            this.kratiseis1 = new HashSet<kratiseis>();
        }
    
        public int kwd { get; set; }
        public string eponimia { get; set; }
        public string titlostimolog { get; set; }
        public string ipeuthinos { get; set; }
        public string dieuthinsi { get; set; }
        public string tilefono { get; set; }
        public string fax { get; set; }
        public string telex { get; set; }
        public string email { get; set; }
        public string afm { get; set; }
        public string doy { get; set; }
        public bool imerisiatimi { get; set; }
        public string logariasmos { get; set; }
        public Nullable<int> xrewsi { get; set; }
        public bool garanti { get; set; }
        public Nullable<short> sentonia { get; set; }
        public Nullable<short> tapeta { get; set; }
        public Nullable<short> petsetes { get; set; }
        public Nullable<short> mpournouzia { get; set; }
        public bool individual { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
        public Nullable<int> property { get; set; }
    
        public virtual ICollection<kratiseis> kratiseis { get; set; }
        public virtual ICollection<kratiseis> kratiseis1 { get; set; }
        public virtual tblproperty tblproperty { get; set; }
    }
}
