//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class simfonies
    {
        public int kwd { get; set; }
        public Nullable<int> simbolaio { get; set; }
        public Nullable<short> aa { get; set; }
        public Nullable<int> tipos { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<float> prwino { get; set; }
        public string prwinomonada { get; set; }
        public Nullable<float> geuma { get; set; }
        public string geumamonada { get; set; }
        public Nullable<float> dipno { get; set; }
        public string dipnomonada { get; set; }
        public Nullable<short> prosauxisisnono { get; set; }
        public Nullable<short> ekptositrito { get; set; }
        public Nullable<short> paidi1klinofree { get; set; }
        public Nullable<short> paidi1klinoews { get; set; }
        public Nullable<int> paidi1klinoekpt { get; set; }
        public Nullable<short> paidi2klinofree { get; set; }
        public Nullable<short> paidi2klinoews { get; set; }
        public Nullable<int> paidi2klinoekpt { get; set; }
        public Nullable<short> paidia1free { get; set; }
        public Nullable<short> paidia1ews { get; set; }
        public Nullable<short> paidia1ekpt { get; set; }
        public Nullable<short> paidia2free { get; set; }
        public Nullable<short> paidia2ews { get; set; }
        public Nullable<int> paidia2ekpt { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    }
}
