//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproperty
    {
        public tblproperty()
        {
            this.dwmatia = new HashSet<dwmatia>();
            this.etaireia = new HashSet<etaireia>();
            this.kratiseis = new HashSet<kratiseis>();
            this.praktoreia = new HashSet<praktoreia>();
            this.simbolaia = new HashSet<simbolaia>();
            this.users = new HashSet<users>();
            this.timologia = new HashSet<timologia>();
            this.tipoi = new HashSet<tipoi>();
        }
    
        public int id { get; set; }
        public int pelatis { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<dwmatia> dwmatia { get; set; }
        public virtual ICollection<etaireia> etaireia { get; set; }
        public virtual ICollection<kratiseis> kratiseis { get; set; }
        public virtual ICollection<praktoreia> praktoreia { get; set; }
        public virtual ICollection<simbolaia> simbolaia { get; set; }
        public virtual ICollection<users> users { get; set; }
        public virtual ICollection<timologia> timologia { get; set; }
        public virtual ICollection<tipoi> tipoi { get; set; }
    }
}
