//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class times
    {
        public int kwd { get; set; }
        public Nullable<int> simfonia { get; set; }
        public Nullable<int> xrewsi { get; set; }
        public Nullable<int> klines { get; set; }
        public Nullable<short> paidi { get; set; }
        public Nullable<short> atoma { get; set; }
        public Nullable<float> timiatomo { get; set; }
        public Nullable<float> ipnos { get; set; }
        public Nullable<float> prwino { get; set; }
        public Nullable<float> geuma { get; set; }
        public Nullable<float> deipno { get; set; }
        public Nullable<float> synolo { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    }
}
