//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeskratisis
    {
        public int kwd { get; set; }
        public Nullable<int> kratisi { get; set; }
        public Nullable<int> timi { get; set; }
        public Nullable<int> xrewsi { get; set; }
        public Nullable<int> touristperiod { get; set; }
        public Nullable<float> ekptosi { get; set; }
        public Nullable<System.DateTime> apo { get; set; }
        public Nullable<System.DateTime> mexri { get; set; }
        public Nullable<byte> imeres { get; set; }
        public Nullable<float> ypnos { get; set; }
        public Nullable<float> prwino { get; set; }
        public Nullable<float> geuma { get; set; }
        public Nullable<float> deipno { get; set; }
        public Nullable<float> extra { get; set; }
        public Nullable<float> synolo { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    
        public virtual kratiseis kratiseis { get; set; }
        public virtual xrewseis xrewseis { get; set; }
    }
}
