//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class timologia
    {
        public int kwd { get; set; }
        public Nullable<int> parastatiko { get; set; }
        public Nullable<System.DateTime> imerominia { get; set; }
        public string seira { get; set; }
        public Nullable<short> aa { get; set; }
        public Nullable<int> praktoreio { get; set; }
        public Nullable<int> simbolaio { get; set; }
        public string eponimia { get; set; }
        public string dieuthinsi { get; set; }
        public string epagelma { get; set; }
        public string afm { get; set; }
        public string doy { get; set; }
        public string aitiologia { get; set; }
        public Nullable<float> sumkathposa { get; set; }
        public Nullable<float> fpa { get; set; }
        public Nullable<float> synola { get; set; }
        public Nullable<float> prokataboli { get; set; }
        public Nullable<float> simetoxi { get; set; }
        public Nullable<float> ypoloipon { get; set; }
        public string pliromi { get; set; }
        public Nullable<float> dimforos { get; set; }
        public bool exoflithi { get; set; }
        public bool akyromeno { get; set; }
        public bool extra { get; set; }
        public bool memonomeno { get; set; }
        public bool mauro { get; set; }
        public Nullable<int> identifikation { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
        public Nullable<int> property { get; set; }
    
        public virtual tblproperty tblproperty { get; set; }
        public virtual timologia timologia1 { get; set; }
        public virtual timologia timologia2 { get; set; }
    }
}
