//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class timologioanalysis
    {
        public int kwd { get; set; }
        public Nullable<int> kratisi { get; set; }
        public Nullable<int> timologio { get; set; }
        public Nullable<short> aa { get; set; }
        public string voucher { get; set; }
        public string onomateponumo { get; set; }
        public Nullable<int> xrewsi { get; set; }
        public Nullable<System.DateTime> apo { get; set; }
        public Nullable<System.DateTime> mexri { get; set; }
        public Nullable<short> imeres { get; set; }
        public Nullable<float> preistag { get; set; }
        public Nullable<float> ypnos { get; set; }
        public Nullable<float> ypnosfpa { get; set; }
        public Nullable<float> prwino { get; set; }
        public Nullable<float> prwinofpa { get; set; }
        public Nullable<float> geuma { get; set; }
        public Nullable<float> geumafpa { get; set; }
        public Nullable<float> deipno { get; set; }
        public Nullable<float> deipnofpa { get; set; }
        public Nullable<float> extra { get; set; }
        public Nullable<float> extrfpa { get; set; }
        public Nullable<float> allinclusiv { get; set; }
        public Nullable<float> allinclusivfpa { get; set; }
        public Nullable<float> sumkathposa { get; set; }
        public Nullable<float> fpa { get; set; }
        public Nullable<float> synola { get; set; }
        public Nullable<float> ekptposo { get; set; }
        public Nullable<float> ekptpososto { get; set; }
        public Nullable<float> ekptimeres { get; set; }
        public Nullable<float> fee { get; set; }
        public bool ekptosi { get; set; }
        public Nullable<int> identifikation { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    }
}
