//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class touristperiodoi
    {
        public int kwd { get; set; }
        public Nullable<int> simbolaio { get; set; }
        public Nullable<System.DateTime> apo { get; set; }
        public Nullable<System.DateTime> mexri { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<short> relperiod { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    }
}
