//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinhotEntities : DbContext
    {
        internal readonly object Connection;

        public WinhotEntities()
            : base("name=WinhotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dwmatia> dwmatia { get; set; }
        public DbSet<enilikes> enilikes { get; set; }
        public DbSet<etaireia> etaireia { get; set; }
        public DbSet<ethnikotites> ethnikotites { get; set; }
        public DbSet<forosdiamonis> forosdiamonis { get; set; }

        internal void SaveChanges(bool v)
        {
            throw new NotImplementedException();
        }

        public DbSet<kratiseis> kratiseis { get; set; }
        public DbSet<paidia> paidia { get; set; }
        public DbSet<praktoreia> praktoreia { get; set; }
        public DbSet<simbolaia> simbolaia { get; set; }
        public DbSet<simfonies> simfonies { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tblproperty> tblproperty { get; set; }
        public DbSet<timeskratisis> timeskratisis { get; set; }
        public DbSet<timologia> timologia { get; set; }
        public DbSet<tipoi> tipoi { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<xrewseis> xrewseis { get; set; }
        public DbSet<afm> afm { get; set; }
        public DbSet<alias> alias { get; set; }
        public DbSet<katigories> katigories { get; set; }
        public DbSet<parastatika> parastatika { get; set; }
        public DbSet<pistwtikes> pistwtikes { get; set; }
        public DbSet<times> times { get; set; }
        public DbSet<timologioanalysis> timologioanalysis { get; set; }
        public DbSet<touristperiodoi> touristperiodoi { get; set; }
    }
}
