//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class xrewseis
    {
        public xrewseis()
        {
            this.timeskratisis = new HashSet<timeskratisis>();
        }
    
        public int kwd { get; set; }
        public string xrewsi { get; set; }
        public string perigrafi { get; set; }
        public bool ypnos { get; set; }
        public bool prwino { get; set; }
        public bool geuma { get; set; }
        public bool deipno { get; set; }
        public byte[] s_ColLineage { get; set; }
        public Nullable<int> s_Generation { get; set; }
        public Nullable<System.Guid> s_GUID { get; set; }
        public byte[] s_Lineage { get; set; }
    
        public virtual ICollection<timeskratisis> timeskratisis { get; set; }
    }
}
